// Generated by scripts/sync-icons.mjs. Do not edit by hand.
export type IconName =
    | 'arrow_back'
    | 'arrow_forward'
    | 'arrow_outward'
    | 'check'
    | 'close'
    | 'contrast'
    | 'download'
    | 'error'
    | 'info'
    | 'mail'
    | 'menu'
    | 'open_in_new'
    | 'search';

export const iconNames: IconName[] = [
    'arrow_back',
    'arrow_forward',
    'arrow_outward',
    'check',
    'close',
    'contrast',
    'download',
    'error',
    'info',
    'mail',
    'menu',
    'open_in_new',
    'search'
];
