// Copies the curated Material Symbols (Sharp, weight 400) into src/assets/icons
// and regenerates the IconName type. Add a name to ICONS and run `npm run icons`.
// Browse names at https://fonts.google.com/icons?icon.style=Sharp
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';

const ICONS = ['arrow_back', 'arrow_forward', 'arrow_outward', 'check', 'close', 'download', 'error', 'info', 'mail', 'menu', 'open_in_new', 'search'];

const require = createRequire(import.meta.url);
const sourceDir = join(dirname(require.resolve('@material-symbols/svg-400/package.json')), 'sharp');
const targetDir = new URL('../src/assets/icons/', import.meta.url).pathname;
const typesFile = new URL('../src/components/icon-names.ts', import.meta.url).pathname;

mkdirSync(targetDir, { recursive: true });
for (const file of readdirSync(targetDir)) {
    if (file.endsWith('.svg')) rmSync(join(targetDir, file));
}

for (const name of ICONS) {
    const svg = readFileSync(join(sourceDir, `${name}.svg`), 'utf8')
        // Size comes from CSS, colour from currentColor
        .replace(/ width="\d+" height="\d+"/, '')
        .replace('<svg ', '<svg fill="currentColor" ');
    writeFileSync(join(targetDir, `${name}.svg`), svg);
}

const union = ICONS.map((name) => `    | '${name}'`).join('\n');
writeFileSync(
    typesFile,
    `// Generated by scripts/sync-icons.mjs. Do not edit by hand.\nexport type IconName =\n${union};\n\nexport const iconNames: IconName[] = ${JSON.stringify(ICONS)};\n`
);

console.log(`Synced ${ICONS.length} icons to src/assets/icons`);
